class StringCombinedRunner{
	public static void main(String[] args){
		String fruit = "Apple";
		String fruitCombined = "I love " + fruit + ".";
		System.out.println(fruitCombined);
		String country = "USA";
		String countryCombined="Country is "+ country+".";
		System.out.println(countryCombined);
		String city = "New York";
		String cityCombined="City is "+city;
		System.out.println(cityCombined);
		String color = "Red";
		String colorCombined="Favourite color is "+color;
		System.out.println(colorCombined);
		String animal = "Tiger";
		String nationalAnimalIs="Our National Animal is "+animal;
		System.out.println(nationalAnimalIs);
		String car = "Honda";
		String carCompany="Car Company is "+car;
		System.out.println(carCompany);
		String profession = "Doctor";
		String professionIs=profession+" treats well";
		System.out.println(professionIs);
		String food = "Pizza";
		String favouriteFood="Favourite food is "+food;
		System.out.println(favouriteFood);
		String drink = "Coffee";
		String drinkingBeverage="Drunk "+drink;
		System.out.println(drinkingBeverage);
		String flower = "Rose";
		String flowerCombined="favourite flower is "+flower;
		System.out.println(flowerCombined);
		String  movie = "Avatar";
		String movieName="Movie name is "+movie;
		System.out.println(movieName);
		String sport = "Football";
		String sportName="Sport name is "+sport;
		System.out.println(sportName);
		String planet = "Mars";
		String planetName="Planet Name is "+planet;
		System.out.println(planetName);
		String superhero = "Superman";
		String superheroName="Superhero name is"+superhero;
		System.out.println(superheroName);
		String book = "Harry Potter";
		String bookName="Book Name is "+book;
		System.out.println(bookName);
		String instrument = "Guitar";
		String instrumentName="Musical Instrument Name is "+instrument;
		System.out.println(instrumentName);
		String emotion = "Joy";
		String emotionStatuts="I felt immense " + emotion + " when I won the game.";
		System.out.println(emotionStatuts);
		String game = "Chess";
		String gameName=game+" is a popular gaming name.";
		System.out.println(gameName);
		String language = "Java";
		String languageLearning="Learning " + language + " is exciting.";
		System.out.println(languageLearning);
		String company = "Google";
		String companyPlace=company + " is a great place to work.";
		System.out.println(companyPlace);
		String actor = "Sudeep";
		String famousActor=actor+ "is a famousActor";
		System.out.println(famousActor);
		String actress = "Ramya";
		String famousActress=actress+ "is a famousActor";
		System.out.println(famousActress);
		String scientist = "Albert Einstein";
		String greatScientist=scientist+" is a greate scientist";
		System.out.println(greatScientist);
		String inventor = "Thomas Edison";
		String famousInventor=inventor+" is famousInventor";
		System.out.println("famousInventor");
		String musician = "Mozart";
		String musicianName=musician+" is famous musician";
		System.out.println(musicianName);
		String composer = "Beethoven";
		String composersongs="Listening to"+composer+" songs is soothing";
		System.out.println(composersongs);
		String poet = "Shakespeare";
		String poetName="The poetry of " + poet + " resonates with me.";
		System.out.println(poetName);
		String author = "J.K. Rowling";
		String famousAuthor=author+" is famous author";
		System.out.println(famousAuthor);
		String  historicalFigure = "Napoleon";
		String historicalFigureName= historicalFigure + " was a remarkable leader.";
		System.out.println(historicalFigureName);
		String landmark = "Eiffel Tower";
		String landmarkVisit="Visiting the " + landmark + " was a dream come true.";
		System.out.println(landmarkVisit);
		String constellation = "Orion";
		String constellationSee="I saw " + constellation + " in the night sky.";
		System.out.println(constellationSee);
		String bodyPart = "Heart";
		String bodyPartBeats="My " + bodyPart + " beats with joy.";
		System.out.println(bodyPartBeats);
		String season = "Spring";
		String seasonColors="I love the colors of " + season + ".";
		System.out.println(seasonColors);
		String weather = "Sunshine";
		String weatherEnjoyment= "Enjoying the " + weather + " makes me happy.";
		System.out.println(weatherEnjoyment);
		String beverage = "Tea";
		String beveargeName="I drink " + beverage;
		System.out.println(beverage);
		String dessert = "Ice Cream";
		String dessertEating="I eat"+ dessert + " every evening.";
		System.out.println(dessertEating);
		String currency = "Dollar";
		String currencyValue="The value of " + currency + " is strong.";
		System.out.println(currencyValue);
		String continent = "Africa";
		String continentDream="I dream of traveling to " + continent + ".";
		System.out.println(continentDream);
		String ocean = "Pacific";
		String oceanSailing="Sailing on the " + ocean + " is on my bucket list.";
		System.out.println(oceanSailing);
		String sea = "Mediterranean";
		String seaSwimming="Swimming in the " + sea + " was refreshing.";
		System.out.println(seaSwimming);
		String mountain = "Everest";
		String mountainClimimg="Climbing " + mountain + " was a challenging adventure.";
		System.out.println(mountainClimimg);
		String island = "Bali";
		String relaxingOnIsland="Relaxing on " + island + " was peaceful.";
		System.out.println(relaxingOnIsland);
		String peninsula = "Florida";
		String livingInPenisula="Living in " + peninsula + " is enjoyable.";
		System.out.println(livingInPenisula);
		String lake = "Victoria";
		String lakeBeauty="The beauty of " + lake + " is breathtaking.";
		System.out.println(lakeBeauty);
		String river = "Nile";
		String riverFlows="The " + river + " flows gracefully.";
		System.out.println(riverFlows);
		String  waterfall = "Niagara Falls";
		String waterfallSound="The sound of " + waterfall + " is mesmerizing.";
		System.out.println(waterfallSound);
		String forest = "Amazon";
		String forestExploring="Exploring the depths of " + forest + " is fascinating.";
		System.out.println(forestExploring);
		String bird = "Eagle";
		String birdName="I saw"+ bird + " in the forest.";
		System.out.println(birdName);
		String fish = "Salmon";
		String fishing="Fishing for " + fish + " is relaxing.";
		System.out.println(fishing);
		String reptile = "Crocodile";
		String reptileName=reptile+" is a reptileName";
		System.out.println(reptileName);
		String amphibian = "Frog";
		String amphibianName=amphibian+" is a amphibian name";
		System.out.println(amphibianName);
		String insect = "Butterfly";
		String insectWings="The wings of a " + insect + " are delicate.";
		System.out.println(insectWings);
		String tree = "Oak";
		String treeShade="The shade of the " + tree + " was refreshing.";
		System.out.println(treeShade);
		String flower2 = "Tulip";
		String flower2Name="Flower2 name is"+flower2;
		System.out.println(flower2Name);
		String plant = "Fern";
		String plantCare="Taking care of a " + plant + " requires patience.";
		System.out.println(plantCare);
		String gemstone = "Diamond";
		String gemstoneSparkle="The sparkle of a " + gemstone + " is captivating.";
		System.out.println(gemstoneSparkle);
		String metal = "Gold";
		String metalAllure="The allure of " + metal + " is timeless.";
		System.out.println(metalAllure);
		String element = "Oxygen";
		String elementBreathing="Breathing " + element + " is essential for life.";
		System.out.println(elementBreathing);
		String constellation2 = "Ursa Major";
		String constellation2Name="The stars in " + constellation2 + " are magnificent.";
		System.out.println(constellation2Name);
		String vehicle = "Spaceship";
		String vehicleThrilling="Traveling in a " + vehicle + " is thrilling.";
		System.out.println(vehicleThrilling);
		String tool = "Hammer";
		String fixingWithTool="Fixing things with a " + tool + " is satisfying.";
		System.out.println(fixingWithTool);
		String gadget = "Smartphone";
		String gadgetName="I can't live without my " + gadget + ".";
		System.out.println(gadgetName);
		String appliance = "Refrigerator";
		String applianceStorage="Storing food in the " + appliance + " keeps it fresh.";
		System.out.println(applianceStorage);
		String furniture = "Sofa";
		String relaxingOnFurniture="Relaxing on the " + furniture + " is comfortable.";
		System.out.println(relaxingOnFurniture);
		String clothing = "Jeans";
		String clothingName="Wearing " + clothing + " makes me feel good.";
		System.out.println(clothingName);
		String city2 = "Bangalore";
		String city2Name="City2 name is"+city2;
		System.out.println(city2Name);
		String fruit2 = "Grape";
		String fruit2Name=fruit2+" is good for health";
		System.out.println(fruit2Name);
		String fruit3 = "Peach";
		String fruit3Name="I enjoy eating"+fruit3;
		System.out.println(fruit3Name);
		String fruit4 = "Strawberry";
		String fruit4Picking="Picking fresh " + fruit4 + " is fun.";
		System.out.println(fruit4Picking);
		String institute = "X-Workz";
		String instituteName=institute+" is an institute in Bangalore.";
		System.out.println(instituteName);
	
		
	}
}